### ISSUE TITLE
Erreur du filtre par taxon

### ISSUE THREAD

**Issue by jpm-cbna** [cbn-alpin/gn_module_conservation_strategy#30]
Le filtre par taxon de la liste des taxons prioritaires provoque l'erreur ci-dessous lorsqu'on cherche un taxon avec "car gla" pour "_Carex glacialis_" par exemple.

L'erreur:
```javascript
ERROR TypeError: Cannot read properties of null (reading 'length')
    at e.project (6.234dc80f129460de456e.js:1:185302)
    at e._next (main.a10f4ef6a8b7fcdd3a6a.js:1:430952)
    at e.next (main.a10f4ef6a8b7fcdd3a6a.js:1:890419)
    at e.notifyNext (main.a10f4ef6a8b7fcdd3a6a.js:1:27570)
    at e._next (main.a10f4ef6a8b7fcdd3a6a.js:1:3757549)
    at e.next (main.a10f4ef6a8b7fcdd3a6a.js:1:890419)
    at e._next (main.a10f4ef6a8b7fcdd3a6a.js:1:890748)
    at e.next (main.a10f4ef6a8b7fcdd3a6a.js:1:890419)
    at e._next (main.a10f4ef6a8b7fcdd3a6a.js:1:431050)
    at e.next (main.a10f4ef6a8b7fcdd3a6a.js:1:890419)
```

**Comment by jpm-cbna** [comment]
Sur la branche "develop", le problème n'est plus présent. Par contre, les noms apparaissent autant de fois qu'il y a de territoire où le taxon est présent.

**Comment by jpm-cbna** [comment]
Finalement, l'erreur existe toujours. Elle est dû [à cette ligne](https://github.com/cbn-alpin/gn_module_conservation_strategy/blob/develop/frontend/app/shared/components/taxa-filter/taxa-filter.component.ts#L116) qui ne prend pas en compte le cas où la réponse est vide.

**Comment by jpm-cbna** [comment]
Corrigé dans la branche "develop" (ba424c85c7369a2261bbf1ab3f80e14137d0ad2f).
